module.exports = {
	MSG_DOWNLOAD_FILE: 'download.this.file.please!',
	IGTV_CLASSNAME_IDENTIFIER: 'lVhHa RNL1l',
	TAGGED_CLASSNAME_IDENTIFIED: 'FFVAD',
	LOADER_CLASSNAME: 'lds-ripple',
	DOWNLOAD_ALL_MODAL_CLASSNAME: 'download-all-modal',
	IDFI_BUTTON: 'IDFI-BUTTON',
	IDFI_BUTTON_DOWNLOAD_ALL: 'IDFI-BUTTON-DL-ALL',
	TOPRIGHT_NAV_CLASSNAME: '_47KiJ',
	TOPRIGHT_NAV_ELEMENT_CLASSNAME: 'Fifk5'
}
