module.exports = {
	MSG_DOWNLOAD_FILE: 'download.this.file.please!',
	IGTV_CLASSNAME_IDENTIFIER: 'lVhHa RNL1l',
	TAGGED_CLASSNAME_IDENTIFIED: 'FFVAD',
	LOADER_CLASSNAME: 'lds-ripple',
	DOWNLOADER_CLASSNAME: 'IDFI-BUTTON',
	TOPRIGHT_NAV_CLASSNAME: '_47KiJ',
	TOPRIGHT_NAV_ELEMENT_CLASSNAME: 'Fifk5',
	TYPE_BULKDOWNLOAD_ICON: 'BULK-DOWNLOAD-ICON'
}
